src/components/Heading/Heading.css, src/components/MapView/MapView.css, src/components/MapView/MapView.js, src/components/MapView/cplaces_geojson.geojson, src/components/MapView/mapview_backup.js, src/components/Navigation/navigation.css, src/components/Navigation/search.css, src/components/PeopleView/PeopleView.js, src/components/TabViewer/TabViewer.css
I fucked up my local so for this pull request merge the commits I've made from Aug 11-Sept 23rd. Once that merge is complete I'm going to reset my local master and remerge with my local branch so I'm back to being up to date and the merge issues we've run into will hopefully be solved. Leave comments where you're unsure about merging so we don't run into that same issue with master breaking like we did last time.
=> Ben branch

src/components/FieldtripView/FieldtripView.js, src/components/PeopleView/PeopleView.js, src/components/RightBar/RightBar.js, src/components/UserNexus/UserNexusModel.js
Added a basic field trip node to the NexusGraph, fixed selecting Fieldtrips crashing the application.
Still need to add edges for field trip nodes.
=> Added basic fieldtrip node, closed issue #55

src/components/TabViewer/model.js
I'm not sure if this solves issue #61 , but it fixes an issue where clicking on certain people crashes the app; these people have no data associated with them, so I added a check to see if they are undefined.
=> Clicking on certain people no longer crashes the app

src/components/RightBar/RightBar.js
I added an extra filter to renderPlaces() to remove any "N/A" places for people with undefined birth/death places.
Should close #62
=> N/A places no longer appear in the PlaceView of certain people

src/components/FieldtripView/FieldtripView.js, src/components/Navigation/Navigation.js, src/components/RightBar/RightBar.js, src/components/TabViewer/model.js
Close #60
I added a check so that if the fieldtrip_id for getFieldtripsById (TabView/model.js:65) is equal to allFieldtrip's id (-1), then it combines the people, places, and stories from  all the fieldTrips.
Co-Authored-By: Daniel Huang <dhuangg@users.noreply.github.com>
=> Fixed allFieldtrip

.gitignore, src/components/TabViewer/model.js
I added an extra check to ensure that no duplicates are added into allFieldtrip. Also ran the code through a linter and added many comments to it as well as changing the code to be a bit more readable.
The change to the .gitignore is for some files the Visual Studio Code and ESLint added.
=>  No more duplicates in allFieldtrip, heavily commented the code

src/components/TabViewer/model.js, src/components/UserNexus/UserNexusModel.js, src/utils.js
Mostly copy-paste in UserNexusModel's createLinkage() to define the relevant people, places, and stories. Also ran it, and utils.js, through a linter, as well as commenting the code and rewriting a few other small functions.
=> people, person, place links completed

src/components/Navigation/SearchComponent.js
Close issue #87
Good ol' if (typeof var !== "undefined"); just make sure that the search object is properly defined.
=> Fixed issue #87

src/components/MapView/MapView.js, src/components/UserNexus/UserNexusModel.js, src/data-stores/DisplayArtifactModel.js
Close issue #107
I could've simply added an undefined check to createPrimaryLinkages(), but I realized that returning null and giving a console warning in the actual get__ByID() functions in DisplayArtifactModel.js would be a more responsible route (I managed to fix this so quickly because I had a warning saying that placeID "N/A" was not valid). Also, this is sort of a data problem since the placeID was N/A and that caused the function to crash.
Then I had to add an extra filter since MapView.js was expecting undefined for bad places but received null instead.
=> Fix for issue #107

src/components/UserNexus/UserNexusModel.js
Close #106
So, the reason why we were getting errors spewed out so much was because the secondary link implementation was causing the same two nodes to be connected in a bunch of different ways via different connecting nodes; sometimes the same node was being linked back to itself. I believe this has something to do with the numerous links getting the same key for React which it really doesn't like.
Currently, the code filters out the redundant links AFTER they are all generated. I'll probably change this so that the repetitive links are never generated in the first place, instead of having to filter them out later on. This would presumably have the benefit of performance, a little, and more importantly it makes more logical sense to check for duplicate links when creating them.
Also …
=> No more 100K errors!

src/components/PlaceView/PlaceView.js, src/components/UserNexus/UserNexusModel.js
Now the duplicate links aren't even created if they are duplicates. Also fixed a prop-type mistake in PlaceView.js
Wasn't expecting copy-paste to work on the first try.
=> Migrated the duplicate link prevention to createLinkages()

src/components/GraphView/GraphView.css, src/components/GraphView/GraphView.js, src/components/Navigation/Navigation.js, src/components/TabViewer/TabViewer.js, src/components/UserNexus/UserNexus.js
Created another folder for GraphView, and currently it renders a blank page. Had to change a couple of functions to make this work, and I commented those functions and rewrote ugly/overly verbose parts of the code. Also formatted the code.
=> Commented a couple of functions, added a template for the new Graph tab

src/components/UserNexus/UserNexus.css, src/components/UserNexus/UserNexus.js, src/components/UserNexus/UserNexusModel.js
Close #10
Added 2 booleans to UserNexus' state to control whether or not primary and secondary links are shown. If false, their respective links are filtered out before the graph is rendered. Also added/edited some comments, and CSS so the 3 buttons look prettier.
Later, as a part of #101, I'll move these buttons to its own tab. For now they will stay on the home screen.
=> Edge filters

src/App.js, src/components/BookView/BookView.js, src/components/Heading/Heading.js, src/components/TabViewer/TabViewer.js, src/reducers/tabViewerReducer.js
Close #129
So I just added a bunch of comments. I was trying to figure out how to update the selected chapter from within the view, but apparently that wasn't necessary. Code is still in place for future use if/when we have to dynamically update the page # from outside the BookView
=> Just...coments... and rewriting some code

src/actions/actionTypes.js, src/actions/tabViewerActions.js, src/components/MapView/MapView.js, src/components/TabViewer/TabViewer.js, src/reducers/tabViewerReducer.js
Close #124
Added a new function for moving a tab at a specific index to a new index. Then I made the tabs draggable, and added a function to detect where tabs are dropped and move the tabs approriately. It's not very pretty or fancy, but the tabs do re-order - I'll probably improve the looks later on. I also ensured that the home tab remains at index 0 (very left), by request of @dhuangg .
Also I removed the console logging in MapView.js because those just spam out the console and make it torturous to see actually relevant logs.
=> Tabs are draggable!

src/components/TabViewer/TabViewer.css, src/components/TabViewer/TabViewer.js
Now, you can see where the tab will be dropped while dragging - also helps you know that the tabs CAN be dragged. Basically just copied the code to find where to move the tab to on release, and used that to render a line in the appropriate location,
=> Purple line to indicate where the tab will be dropped while dragging

src/components/FieldtripView/FieldtripView.js, src/components/MapView/MapView.js, src/components/Navigation/Navigation.js, src/components/Navigation/NavigationDropdownMenu.js, src/components/Navigation/NavigatorComponent.js, src/components/Navigation/SearchComponent.js, src/components/NexusGraph/NexusGraph.js, src/components/NexusGraph/NexusGraphModel.js, src/components/PeopleView/PeopleView.js, src/components/PlaceView/PlaceView.js, src/components/RightBar/RightBar.js, src/components/StoryView/StoryView.js, src/components/TabViewer/TabViewer.js, src/data-stores/DisplayArtifactModel.js, src/data-stores/SessionStorageModel.js, src/reducers/initialState.js, src/reducers/tabViewerReducer.js, src/utils.js
Close #83, #142
Just went through the files and looked for useless/poorly written code and fixed it, also tried to add comments to the files. Unexpectedly happened to reveal story markers on mapview lol. Also did some minor fixes mostly related to bad/undefined data
=>  Rewrote a lot of code, added some comments, fixed a couple of things

src/components/TabViewer/TabViewer.js
This mostly was about the drag and drop functionality of tabs. I was using the exact same code to calculate the index where the tab would be dropped. This code was used in both handleDrag (callback called while the tab is being dragged) and handleDragEnd (callback called when the tab is released). Moved it to a separate function for simplicity and clarity. No functionality was changed.
=> Re-organized tab viewer code a bit

src/components/TabViewer/TabViewer.js
Close #160
So Firefox is annoying and makes you set a few things before you can actually drag things, and uses alternate callbacks for drags. I ended up having to store the original and final indices of the drag to the TabViewer class so that I can actually use them in firefox. At least this method is compatible with Safari.
=> Drag and drop functionality for Firefox

package-lock.json, package.json, src/components/BookView/BookView.css, src/components/BookView/BookView.js, src/components/Heading/Heading.js, src/components/TabViewer/TabViewer.js
Close #144 
It's not a super fancy search engine but I migrated the book view to ePub.js; I installed that package from npm and removed react-reader because it is no longer needed. Then I used a code snippet from ePub's wiki to implement the search, and created a second screen for displaying search results.
=> Search through book feature

src/components/Heading/Heading.js, src/components/HelpView/HelpView.css, src/components/HelpView/HelpView.js, src/components/TabViewer/TabViewer.js
Just added a button that opens up a help tab, as well as a really basic template for the actual help view.
=> Added a help button and a template for a help view

src/components/Navigation/NavigationDropdownMenu.js, src/components/Navigation/NavigatorComponent.js
I was too scared to try and fix the mapview zoom issue, so I did this instead. Made stuff more logical (I think?); this might be something to migrate to Redux, but I'm not sure.
=> Code rewrites (again)

src/components/StoryView/StoryView.css, src/components/StoryView/StoryView.js
Added a button to toggle between the default story view and a version with an enlarged map and the story text.
=> Expanded Map option in StoryView

src/components/BookView/BookView.css, src/components/BookView/BookView.js
Added two buttons, a and A, to increase/decrease the font size of the book, within bounds. Uses the book's provided font resizing.
=> Book font sizing option

src/components/BookView/BookView.js, src/components/FieldtripTool/FieldtripTool.js, src/components/HelpView/HelpView.js, src/components/Navigation/Navigation.js, src/components/NexusGraph/GraphView.js, src/components/StoryView/StoryView.js, src/components/TabViewer/TabViewer.js
State is saved to Redux when a tab is switched away from (if there is a state to save), and state is loaded from Redux whenever a tab is switched to (if there is a saved state).
=> State is saved on switched tab

src/components/BookView/BookView.css, src/components/BookView/BookView.js, src/components/Heading/Heading.js, src/components/StoryView/StoryView.js, src/components/TabViewer/TabViewer.js, src/data/book_menu_old.json, src/reducers/tabViewerReducer.js
Fixed "empty" tabs, altered the ToC - removed the pre-text and post-text tabs, since they are not in the current ePub. Fixed a couple of formatting errors, the in-book ToC matches the header's ToC. Opening chapters via the header should consistently work now.
=> Fixed a couple of bugs with the book
